### ISSUE TITLE
Remove CSV export

### ISSUE THREAD

**Issue by ledsoft** [kbss-cvut/termit-ui#389]
# Description
Given the complex nature of the data (especially multilingual string-based attributes of terms), the CSV export is almost unusable (practically impossible to open in a tabular processor like Excel or Libre Office Calc without major changes to the content). Its usefulness is thus extremely limited and the feature should be removed.

**Comment by blcham** [comment]
Just an idea (we don't need it anywhere), i am just said that we are going with non-proprietary format only (but maybe it is ok since we have ttl at least).

Is excel effectively "just set of csv files" -- or it is more complicated than that? Maybe it would be nice to have at least functionality on backend to retrieve certain TABs related to whole excel -- thus REST API endpoint would have parameter identifying the tab you want to retrieve from the excel (e.g. language="en"). In case parameter is not specified download all csv files in zip which would throw NotImplementedException now :).
