### ISSUE TITLE
Inconsistency between vocabulary list and vocabulary detail in UI

### ISSUE THREAD

**Issue by psiotwo** [kbss-cvut/termit-ui#45]
Public deploy at https://kbss.felk.cvut.cz/termit-kodi-public lists a vocabulary "265/2000". 

![image](https://user-images.githubusercontent.com/1140626/98668350-0a2cdc00-2350-11eb-9cc0-20ba46eb1a1c.png)

When clicking on detail, the vocabulary is shown as "**3**65/2000".

This was caused by having updated the data on the backend from 265/2000 to 365/2000 outside of TermIt while having TermIt running. In this sense, having stale data is correct behaviour. What is incorrect is that TermIt UI can display inconsistent information based on internal decision what to cache and what to not cache.

![image](https://user-images.githubusercontent.com/1140626/98669043-15ccd280-2351-11eb-8fdd-8da704a72875.png)

**Comment by ledsoft** [comment]
1. I don't understand why this issue is reported here. If it is KBSS version, it should be in Redmine according to the rules you stated). If it's KODI version, it should be in the KODI repositories.
2. What TermIt cache do you mean?
3. When did the update in repository data occur? I'm having trouble understanding the described issue (or rather the sequence of events that lead to it).
4. I'm not even sure whether this is a bug. Based on my understanding, this would be equally likely to happen with JPA. If we bypass the persistence provider and modify data in repository directly, it is highly likely we will end up with incorrect/stale data being processed by the application. Either we want the caches to optimize the application performance, or we want to mess with data directly and in that case all the caches should be disabled...

**Comment by ledsoft** [comment]
Stale issue, closing.
